
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author athir
 */
public class cost extends javax.swing.JFrame {

    /**
     * Creates new form cost
     */
    String id;
    public cost(String id)
    {  initComponents();
       this.id=id;
    }
    public cost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tcost = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        ecost = new javax.swing.JTextField();
        vcost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        esel = new javax.swing.JComboBox<>();
        vsel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(66, 103, 101));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 255, 244));
        jLabel4.setText("COST");

        tcost.setEditable(false);
        tcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcostActionPerformed(evt);
            }
        });

        pay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pay.setText("PROCEED TO PAYEMENT");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        calculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculate.setText("CALCULATE");
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
        });
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        ecost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        vcost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(66, 103, 101));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 255, 244));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EVENT DETAILS");

        jLabel1.setBackground(new java.awt.Color(66, 103, 101));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 255, 244));
        jLabel1.setText("EVENT");

        jLabel2.setBackground(new java.awt.Color(66, 103, 101));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 255, 244));
        jLabel2.setText("VENUE");

        esel.setBackground(new java.awt.Color(66, 103, 101));
        esel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        esel.setForeground(new java.awt.Color(243, 255, 244));
        esel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMINAR", "PRESS_CONFERENCE", "MUSIC_LAUNCH" }));
        esel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eselActionPerformed(evt);
            }
        });

        vsel.setBackground(new java.awt.Color(66, 103, 101));
        vsel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vsel.setForeground(new java.awt.Color(243, 255, 244));
        vsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIVANTA", "St.PETER", "VS AUDITORIUM", "ANASHWARA HALL ", "TOWN HALL" }));
        vsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vselActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(66, 103, 101));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 255, 244));
        jLabel3.setText("EVENT");

        jLabel6.setBackground(new java.awt.Color(66, 103, 101));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 255, 244));
        jLabel6.setText("VENUE");

        jLabel7.setBackground(new java.awt.Color(66, 103, 101));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(243, 255, 244));
        jLabel7.setText("EXPECTED GUESTS");

        jLabel8.setBackground(new java.awt.Color(66, 103, 101));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(243, 255, 244));
        jLabel8.setText("DATE");

        exp.setBackground(new java.awt.Color(66, 103, 101));
        exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exp.setForeground(new java.awt.Color(243, 255, 244));
        exp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(66, 103, 101));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(243, 255, 244));
        jTextField2.setText("(100-500)");
        jTextField2.setBorder(null);

        date.setBackground(new java.awt.Color(66, 103, 101));
        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(243, 255, 244));
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(243, 255, 244)));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(66, 103, 101));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(243, 255, 244));
        jTextField4.setText("DD-MM-YY");
        jTextField4.setBorder(null);

        jLabel9.setBackground(new java.awt.Color(66, 103, 101));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(243, 255, 244));
        jLabel9.setText("ID");

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(66, 103, 101));
        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(243, 255, 244));
        ID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(243, 255, 244)));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2)
                    .addComponent(exit)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(exp, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ecost, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vcost, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(162, 162, 162)
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66)
                                .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(vsel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(esel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(160, 160, 160)
                                .addComponent(calculate)))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pay)
                        .addGap(104, 104, 104))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculate)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exit)
                            .addComponent(pay))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(esel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addComponent(vsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ecost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(142, 142, 142))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new userlogin().setVisible(true);
    }//GEN-LAST:event_exitMouseClicked

    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked
        // TODO add your handling code here:
         double cost;
         double tax;
         double sum;
         final double taxrate = 0.05;
         double event;
         double venue;
         event = Double.parseDouble(ecost.getText());
         venue = Double.parseDouble(vcost.getText());
         sum = event + venue ;
         tax = sum * taxrate;
         cost = tax + sum;
         tcost.setText(Double.toString(cost));
    }//GEN-LAST:event_calculateMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_payMouseClicked

    private void eselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eselActionPerformed
        // TODO add your handling code here:
        double SEMINAR = 5000.0;
         double PRESS_CONFERENCE = 10000.0;
         double MUSIC_LAUNCH = 15000.0;
         if (esel.getSelectedItem().equals("SEMINAR"))
         { ecost.setText(Double.toString(SEMINAR));
         
         }
         if (esel.getSelectedItem().equals("PRESS_CONFERENCE"))
         { ecost.setText(Double.toString(PRESS_CONFERENCE));
         
         }
         if (esel.getSelectedItem().equals("MUSIC_LAUNCH"))
         {
             ecost.setText(Double.toString(MUSIC_LAUNCH));
         }
         /*double VIVANTA = 100000;
         double St = 75000.0;
         double VS = 50000.0;
         double AP = 25000.0;
         double TOWN = 15000.0;
         if (vsel.getSelectedItem().equals("VIVANTA"))
         { vcost.setText(Double.toString(VIVANTA));
         
         }
         if (vsel.getSelectedItem().equals("St"))
         { vcost.setText(Double.toString(St));
         
         }
         if (vsel.getSelectedItem().equals("VS"))
         {
             vcost.setText(Double.toString(VS));
         }
         if (vsel.getSelectedItem().equals("AP"))
         { vcost.setText(Double.toString(AP));
         
         }
         if (vsel.getSelectedItem().equals("TOWN"))
         {
             vcost.setText(Double.toString(TOWN));
         }*/
    }//GEN-LAST:event_eselActionPerformed

    private void vselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vselActionPerformed
        // TODO add your handling code here:
        double VIVANTA = 100000;
         double St = 75000.0;
         double VS = 50000.0;
         double AP = 25000.0;
         double TOWN = 15000.0;
         if (vsel.getSelectedItem().equals("VIVANTA"))
         { vcost.setText(Double.toString(VIVANTA));
         
         }
         if (vsel.getSelectedItem().equals("St.PETER"))
         { vcost.setText(Double.toString(St));
         
         }
         if (vsel.getSelectedItem().equals("VS AUDITORIUM"))
         {
             vcost.setText(Double.toString(VS));
         }
         if (vsel.getSelectedItem().equals("ANASHWARA HALL"))
         { vcost.setText(Double.toString(AP));
         
         }
         if (vsel.getSelectedItem().equals("TOWN HALL"))
         {
             vcost.setText(Double.toString(TOWN));
         }
    }//GEN-LAST:event_vselActionPerformed

    private void tcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcostActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        String vname = vsel.getItemAt(vsel.getSelectedIndex());
        String mail = ID.getText();
        double cost;
        cost = Double.parseDouble(tcost.getText());
        String evtype = esel.getItemAt(esel.getSelectedIndex());
        String ex_guest  = exp.getText();
        String doe = date.getText();
        int out=0;
        int count=0;
        try {
            String driverName="oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            Connection conn;
            conn =DriverManager.getConnection("jdbc:oracle:thin:@DESKTOP-0EPDHK7:1521:XE","athira","pillai");
            if(conn!=null)
            { System.out.println("SUCCESSFULL!!");}
            else
            {System.out.println("NOT SUCCESSFULL!!");}
            String sql;
            sql="select count(*) from EVENT where DOE='"+doe+"'";
            System.out.println(sql);
            /*Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            System.out.println(rs.next());
            if(rs.next()==true)
            { JOptionPane.showMessageDialog(null,"DATE ALREADY BOOKED FOR ANOTHER EVENT!!","Error",JOptionPane.INFORMATION_MESSAGE); }*/
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
               count=rs.getInt(1);
            if(count==1)
            { JOptionPane.showMessageDialog(null, "ALREADY BOOKED FOR ANOTHER EVENT!! INSERT ANOTHER DATE","Error",JOptionPane.INFORMATION_MESSAGE);
            }
            
            else
            {
                String query;
                query = "Insert into EVENT values('"+vname+"','"+mail+"','"+cost+"','"+evtype+"','"+ex_guest+"','"+doe+"')";
                int rst;
                Statement smt = conn.createStatement();
                rst = smt.executeUpdate(query);
                System.out.println("RECORD INSERTED");
                out = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO PROCEED TO PAYMENT","Payment",JOptionPane.YES_NO_OPTION);
                if(out == JOptionPane.YES_OPTION){
                this.setVisible(false);
                new payment().setVisible(true);
            } 
                else if(out == JOptionPane.NO_OPTION){
                            new cost().setVisible(true);}
            }
        }
        catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_payActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
                   // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ID.setText(this.id);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField date;
    private javax.swing.JTextField ecost;
    private javax.swing.JComboBox<String> esel;
    private javax.swing.JButton exit;
    private javax.swing.JTextField exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton pay;
    private javax.swing.JTextField tcost;
    private javax.swing.JTextField vcost;
    private javax.swing.JComboBox<String> vsel;
    // End of variables declaration//GEN-END:variables
}
